version: "3"
services:
 reverseproxy:
    build:
      context: .
    image: muratovic/reverseproxy 
 backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: muratovic/udacity-restapi-user
 backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed 
    image: muratovic/udacity-restapi-feed
 frontend:
    build:
      context: ../../udacity-c3-frontend 
    image: muratovic/udacity-frontend:local
